---
# AWS Configuration
aws_region: "{{ lookup('env', 'AWS_REGION')} }"
db_secret_name: "{{ lookup('env', 'DB_SECRET_NAME') }}"

# Docker Images  
backend_image: "{{ lookup('env', 'ECR_BACKEND_REPO') }}:latest"
backend_port: 3000
