name: Build & Push Docker Images

on:
  push:
    branches:
      - staging
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  DB_SECRET_NAME: ${{ secrets.DB_SECRET_NAME }} 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v2

      # Backend Image
      - name: Build & Push Backend Image
        env:
          ECR_BACKEND_REPO: ${{ secrets.ECR_BACKEND_REPO }}
        run: |
          BACKEND_TAG=backend:${GITHUB_SHA::8}
          docker build --cache-from $ECR_BACKEND_REPO:backend-latest -t $ECR_BACKEND_REPO:$BACKEND_TAG ./backend
          docker tag $ECR_BACKEND_REPO:$BACKEND_TAG $ECR_BACKEND_REPO:backend-latest
          docker push $ECR_BACKEND_REPO:$BACKEND_TAG
          docker push $ECR_BACKEND_REPO:backend-latest

      # Frontend Image
      - name: Build & Push Frontend Image
        env:
          ECR_FRONTEND_REPO: ${{ secrets.ECR_FRONTEND_REPO }}
        run: |
          FRONTEND_TAG=frontend:${GITHUB_SHA::8}
          docker build --cache-from $ECR_FRONTEND_REPO:frontend-latest -t $ECR_FRONTEND_REPO:$FRONTEND_TAG ./frontend
          docker tag $ECR_FRONTEND_REPO:$FRONTEND_TAG $ECR_FRONTEND_REPO:frontend-latest
          docker push $ECR_FRONTEND_REPO:$FRONTEND_TAG
          docker push $ECR_FRONTEND_REPO:frontend-latest

      #Trigger Ansible Deployment
      - name: Trigger Ansible Deployment
        uses: dawidd6/action-ansible@v2
        with:
          playbook: ansible/playbooks/site.yml
          inventory: ansible/aws_ec2.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          AWS_REGION: ${{ env.AWS_REGION }}
          DB_SECRET_NAME: ${{ env.DB_SECRET_NAME }}
